"""add share_token to routes

Revision ID: 7b3c81c09487
Revises: 78bc43d3c2b0
Create Date: 2026-05-25 01:45:43.182261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3c81c09487'
down_revision = '78bc43d3c2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_routes_share_token', ['share_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_routes_share_token', type_='unique')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
